version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - ../:/data/projects/biletum
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/log:/var/log/container/
    depends_on:
      - php-fpm
    networks:
      - internal

  php-fpm:
    build: ./docker/php-fpm
    working_dir: /data/projects/biletum/gillix/
    volumes:
      - ../:/data/projects/biletum
      - ./docker/log:/var/log/container
    environment:
      XDEBUG_REMOTE_ENABLE: ${XDEBUG_REMOTE_ENABLE}
      XDEBUG_REMOTE_AUTOSTART: ${XDEBUG_REMOTE_AUTOSTART}
      XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
      XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
      XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
      XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}
    networks:
      - internal


networks:
  internal:
    driver: bridge
